name: make build with action

on:
  push:
    branches: [main]

jobs:
  build-vite-app-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.x
      - name: install deps
        run: npm install
      - name: make the build of the code
        run: npm run build
      - name: Show the build
        run: ls -la
